### ISSUE TITLE
Cases section: make smaller & highlight categories

### ISSUE THREAD

**Issue by iamakulov** [3perf/website#55]
### Challenge

[The “Cases” section](https://3perf.com/#clients) on the home page grew to be large, and I find it hard to read and navigate. As we’ll keep adding more client feedbacks, it will become even larger and harder to read. It’s time to adapt the design to this.

### Proposed solution

- [ ] Reorg the desktop “Cases” UI to look as follows:
    <img width="1552" alt="Screen Shot 2021-09-20 at 00 53 39" src="https://user-images.githubusercontent.com/2953267/133944226-a613d2e3-7e37-45ad-a06f-d2d9f2cf3a72.png">

   Key changes (on desktop only):
   * Two columns instead of one
      * The column gap is `72px`
   * Spacing between items increased to `48px`
   * Font size of the whole section changed to `16px`

- [ ] Tune the mobile “Cases” UI to apply `font-size: 0.75em` to company descriptions (like on desktop):

   <img src="https://user-images.githubusercontent.com/2953267/133944450-9654ffdf-3602-4655-b234-f5448ac7bbe1.png" width="300" />
   
- [ ] For each case, add tags that would highlight what we’ve done with each client:

  <img width="503" alt="Screen Shot 2021-09-20 at 01 05 33" src="https://user-images.githubusercontent.com/2953267/133944501-56baa765-ee65-40f0-a41d-887ba718ef34.png">
  
  (For now, tags would stay non-interactive.)
  
  Styles I used for this screenshot (just as a reference – you’re welcome to tune/reorganize if needed):
  
  ```css
  .tags-container {
    margin-top: 8px;
  }
  
  .tag {
    display: inline-block;
    background: #ffdb01; /* This is colors.brightYellow */
    padding: 2px 8px;
    border-radius: 2px;
    margin-right: 8px;
  }
  ```
  
  Here’s which tags each client would have:
  
  * Google: #education
  * Framer: #react-performance #build-performance #core-web-vitals
  * Castor: #react-performance #core-web-vitals
  * Appsmith: #react-performance #core-web-vitals
  * Common: #core-web-vitals
  * Fat Llama: #core-web-vitals
